import { Specimen } from '../../types';

export const testSpecimen: Specimen = {
  associatedReferences: '',
  associatedSequences: '',
  box: '2',
  catalogNumber: 'MGCL_123467',
  collectedDay: 11,
  collectedMonth: 11,
  collectedYear: 2018,
  coordinateUncertainty: '',
  country: 'Madagascar',
  county: 'Ifanadiana',
  dateEntered: null,
  dateIdentified: '',
  decimalLatitude: -21.253909,
  decimalLongitude: 47.421911,
  disposition: '',
  elevationInMeters: '',
  family: '',
  fieldNotes: '',
  freezer: '',
  genus: '',
  geodeticDatum: '',
  georeferencedBy: '',
  habitat: '',
  id: 3,
  identificationQualifier: '',
  identifiedBy: '',
  infraspecificEpithet: null,
  isLoaned: '',
  lifeStage: '',
  loanDate: 'undefined',
  loanInstitution: '',
  loanReturnDate: '',
  loaneeName: '',
  locality: 'Centre ValBio Station',
  modifiedInfo: `[{"2020-08-26":{"modifiedBy":"aaronleopold","fieldsChanged":[{"field":"catalogNumber","oldValue":"","newValue":"MGCL_123456"}],"reasonForChanges":"this is just a test"}},{"2020-08-26":{"modifiedBy":"aaronleopold","fieldsChanged":[{"field":"catalogNumber","oldValue":"MGCL_123456","newValue":""}],"reasonForChanges":"just another test"}},{"2020-08-26":{"modifiedBy":"aaronleopold","fieldsChanged":[{"field":"catalogNumber","oldValue":"","newValue":"MGCL_123467"}],"reasonForChanges":"another test"}}]`,
  molecularOccurrenceRemarks: '',
  municipality: 'Ranomafana',
  occurrenceRemarks: '',
  order_: 'Lepidoptera',
  otherCatalogNumber: 'LEP75597',
  otherCollectors: 'Rubin,Juliette | Barber,Jesse',
  preparations: '',
  rack: 'GGG',
  reared: '',
  recordEnteredBy: null,
  recordNumber: '',
  recordedBy: 'Kawahara,Akito',
  samplingProtocol: '',
  sex: null,
  specificEpithet: '',
  stateProvince: 'Vatovavy-Fitovinany',
  subfamily: '',
  subgenus: '',
  superfamily: '',
  tribe: '',
  tubeSize: 'microcentrifuge',
  verbatimDate: '',
  verbatimLatitude: '',
  verbatimLongitude: '',
  withholdData: '',
};
