import checkHeaders from './insertChecks/checkHeaders'

const header1 = [
    'ORDER',
    'SUPERFAMILY',
    'FAMILY',
    'SUBFAMILY',
    'TRIBE',
    'SECTION',
    'GENUS',
    'SPECIES',
    'SUBSPECIES',
    'SEX',
    'COUNTRY',
    'PROVINCE',
    'LOCALITY',
    'Latitude',
    'Longitude',
    'ELEVATION',
    'MV',
    'DAYS',
    'MONTH',
    'YEAR',
    'COLLECTORS',
    'FREEZER',
    'RACK',
    'BOX',
    'SIZE',
    'Note',
]

const header2 = [
    'MGCL',
    'LEP #',
    'ORDER',
    'SUPERFAMILY',
    'FAMILY',
    'SUBFAMILY',
    'TRIBE',
    'SECTION',
    'GENUS',
    'SPECIES',
    'SUB-SPECIES',
    'SEX',
    'COUNTRY',
    'PROVINCE',
    'LOCALITY',
    'Latitude',
    'Longitude',
    'ELEVATION',
    'MV',
    'DAYS',
    'MONTH',
    'YEAR',
    'COLLECTORS',
    'FREEZER',
    'RACK',
    'BOX',
    'SIZE',
    'Note',
]

const header3 = [
    'MGCL',
    'LEP #',
    'ORDER',
    'SUPERFAMILY',
    'FAMILY',
    'SUBFAMILY',
    'TRIBE',
    'SECTION',
    'SPECIES',
    'GENUS',
    'SUBSPECIES',
    'SEX',
    'COUNTRY',
    'PROVINCE',
    'LOCALITY',
    'Latitude',
    'Longitude',
    'ELEVATION',
    'MV',
    'DAYS',
    'MONTH',
    'YEAR',
    'COLLECTORS',
    'FREEZER',
    'RACK',
    'BOX',
    'SIZE',
    'Note',
]

test('correct headers', async () => {
    await expect(checkHeaders(header1)).toEqual(false)
    await expect(checkHeaders(header2)).toEqual(true)
    await expect(checkHeaders(header3)).toEqual(false)
})