import { types } from 'mobx-state-tree';

// TODO: not sure if I want to do this
export const Specimen = types.model({
  catalogNumber: types.string, // MGCL-123456
  otherCatalogNumber: types.string, // LEP123456
  recordNumber: types.string,
  order_: types.string,
  superfamily: types.string,
  family: types.string,
  subfamily: types.string,
  tribe: types.string,
  genus: types.string,
  subgenus: types.string,
  specificEpithet: types.string,
  infraspecificEpithet: types.string,
  identificationQualifier: types.string,
  recordedBy: types.string, // First Last | First Last
  otherCollectors: types.string,
  identifiedBy: types.string,
  dateIdentified: types.string,
  verbatimDate: types.string,
  collectedYear: types.number,
  collectedMonth: types.number,
  collectedDay: types.number,
  // sex: 'M' | 'F' | 'G',
  lifeStage: types.string,
  habitat: types.string,
  occurrenceRemarks: types.string,
  molecularOccurrenceRemarks: types.string,
  samplingProtocol: types.string,
  country: types.string,
  stateProvince: types.string,
  county: types.string,
  municipality: types.string,
  locality: types.string,
  elevationInMeters: types.string,
  decimalLatitude: types.string,
  decimalLongitude: types.string,
  geodeticDatum: types.string,
  coordinateUncertainty: types.string,
  verbatimLatitude: types.string,
  verbatimLongitude: types.string,
  georeferencedBy: types.string,
  disposition: types.string,
  isLoaned: types.string,
  loanInstitution: types.string,
  loaneeName: types.string,
  loanDate: types.string,
  loanReturnDate: types.string,
  preparations: types.string,
  freezer: types.string,
  rack: types.string,
  box: types.string,
  tubeSize: types.string,
  associatedSequences: types.string,
  associatedReferences: types.string,
  withholdData: types.string,
  reared: types.string,
  fieldNotes: types.string,
});
